# Generated by Django 3.2.16 on 2022-12-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstatus',
            options={'get_latest_by': 'petId'},
        ),
    ]
