# Generated by Django 3.2.16 on 2022-12-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
