# Generated by Django 3.2.16 on 2022-12-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetModel', '0002_auto_20221204_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToDict',
            fields=[
                ('commentId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('totalAgree', models.IntegerField()),
                ('comment', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DictCommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.commenttodict')),
            ],
        ),
        migrations.CreateModel(
            name='DictPetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=128, unique=True)),
                ('image1', models.ImageField(null=True, upload_to='pettypeimg/', verbose_name='PetTypeImage')),
            ],
        ),
        migrations.CreateModel(
            name='PetStatus',
            fields=[
                ('petId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='petimage/', verbose_name='PetImage')),
                ('grow', models.IntegerField()),
                ('hunger', models.IntegerField()),
                ('clean', models.IntegerField()),
                ('active', models.IntegerField()),
                ('healthy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetTask',
            fields=[
                ('taskId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=128)),
                ('isFinish', models.BooleanField()),
                ('growPet', models.IntegerField()),
                ('growType', models.IntegerField()),
                ('growValue', models.IntegerField()),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.petstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('type', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('typeName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PetTypePetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.petstatus')),
                ('petType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.pettype')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.petinfo', to_field='variety')),
            ],
            options={
                'unique_together': {('petType', 'variety', 'petId')},
            },
        ),
        migrations.CreateModel(
            name='RightsDescription',
            fields=[
                ('rights', models.IntegerField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('account', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=16)),
                ('money', models.BigIntegerField()),
                ('describe', models.CharField(max_length=256)),
                ('image', models.ImageField(null=True, upload_to='usrimg/', verbose_name='UserImage')),
                ('rights', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.rightsdescription')),
            ],
        ),
        migrations.CreateModel(
            name='UserToPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.petstatus')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.userinfo')),
            ],
            options={
                'unique_together': {('userId', 'petId')},
            },
        ),
        migrations.CreateModel(
            name='ValuableBook',
            fields=[
                ('dictId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('likedNum', models.IntegerField()),
                ('commentNum', models.IntegerField()),
                ('forwardNum', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=1024)),
                ('video', models.CharField(max_length=256)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.userinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='petstatus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.pettype'),
        ),
        migrations.AddField(
            model_name='petstatus',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.petinfo', to_field='variety'),
        ),
        migrations.AddField(
            model_name='petinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.pettype'),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='userId1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userId1', to='PetModel.userinfo'),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='userId2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userId2', to='PetModel.userinfo'),
        ),
        migrations.AddField(
            model_name='dictpetrelation',
            name='petType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.pettype'),
        ),
        migrations.AddField(
            model_name='dictpetrelation',
            name='valuableBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.valuablebook'),
        ),
        migrations.AddField(
            model_name='dictpetrelation',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.petinfo', to_field='variety'),
        ),
        migrations.AddField(
            model_name='dictcommentrelation',
            name='dictId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PetModel.valuablebook'),
        ),
        migrations.AlterUniqueTogether(
            name='petinfo',
            unique_together={('type', 'variety')},
        ),
        migrations.AlterUniqueTogether(
            name='friendrelation',
            unique_together={('userId1', 'userId2')},
        ),
        migrations.AlterUniqueTogether(
            name='dictpetrelation',
            unique_together={('petType', 'variety', 'valuableBook')},
        ),
        migrations.AlterUniqueTogether(
            name='dictcommentrelation',
            unique_together={('dictId', 'commentId')},
        ),
    ]
